### PR TITLE
"external authorization data" EAD

### PR DESCRIPTION
**Pull request by emanjon**

### CODE REVIEW

**Comment by emanjon** [comment]
The definition says array but the CDDL is a CBOR sequence. In this case it works to use a sequence.

The CDDL for message_1, 2 3 4 needs to be updated. Right now they say 

? EAD_1 : any,

**Comment by emanjon** [comment]
Might also want to allow more that one CBOR item. The following would be quite general:

EAD = (
  type : int,
  + ext_authz_data,
)

? EAD_1 : EAD,

Should probably write that "+ ext_authz_data," follows from "type : int,"







Extensions = [ * Extension ] / int

Extension = ( extensionID: int, extensionValue: any ) //
            ( extensionID: ~oid, critical: bool, extensionValue: bytes )
 )

**Comment by marco-tiloca-sics** [comment]
Looks good.

**Comment by emanjon** [comment]
Was there any reason that this was not merged today. The new IANA registry for Aux Data should probably be another PR.

**Comment by gselander** [comment]
The reason for not merging this yet was to first conclude the discussion about CWT in EAD_2 and EAD_3 in #90.

**Comment by gselander** [comment]
By moving out the IANA type to a separate issue #126 and waiting with the CWT related part of #90 we are ready to merge.

**Pull request merged**
