### PR TITLE
Optimization of message_2 to 45 bytes

### PR DESCRIPTION
**Pull request by emanjon**

### CODE REVIEW

**Comment by emanjon** [comment]
message_2 could be made 44 bytes by using the known length of SIGNATURE_OR_MAC_2

**Comment by marco-tiloca-sics** [comment]
I suggest to have C_R as the last element of the CBOR sequence (which shouldn't be a problem and still allows for a sequential sequence parsing), i.e.:

```
~~~~~~~~~~~ CDDL
data_2 = (
  G_Y_CIPHERTEXT_2 : bstr,
  C_R : bstr / int
)
~~~~~~~~~~~
```

When using CoAP (or other transports with the same correlation properties), this would preserve a current good pattern as useful for message recognition: if a response transporting an EDHOC message starts with a CBOR integer, then it's an EDHOC error message.

It would be good to preserve this, hence why keeping C_R at the end of the new message_2, since it can now be either a CBOR byte string or a CBOR integer.

**Review by gselander — APPROVED** [review]

**Comment by gselander** [comment]
Merging this now as there was no objection to:
https://mailarchive.ietf.org/arch/msg/lake/wFREGTMBkR5LEcw3JAksJ782eCk/

This provides a solution to the concrete issue raised in #103.

**Comment by gselander** [comment]
Mistake, I intended to merge, not close.

**Pull request merged**
