### PR TITLE
Add new formal analysis paper

### PR DESCRIPTION
**Pull request by charlie-j**
Hi all,

Our previous formal analysis on draft 12 and 14 lead to a publication at USENIX 23 available here https://hal.inria.fr/hal-03810102/.

As the two other previous formal analysis were cited in the draft, I'm proposing to add next to them our new one with this PR.

As a side remark, our models are here (https://github.com/charlie-j/edhoc-formal-analysis), and we are trying to update everything according to draft 17 with a new overall pass. It might be tight for IETF115, but we are trying our best! And anyway, it should only be positive results by now ;)

### CODE REVIEW

**Comment by gselander** [comment]
@charlie-j Thanks! Great that you follow up with the latest version. The latest relevant changes are probably in -16 and only adds things to the key derivation (some of which was proposed by you :-).

**Comment by charlie-j** [comment]
Thanks for the pointer! Though, the biggest issue is not so much updating the model of the protocol, but rather making a new full pass on the security claims and new appendices,  trying to have a clear systematized link between claims from the draft and what we check in the model.

**Comment by emanjon** [comment]
@gselander let's check if there are some other papers missing and what we want to say about them.

**Comment by gselander** [comment]
We should at least add references to work by ETH and ENS. Let's merge this as a starting point and continue discussion in #350.

**Pull request merged**
