### PR TITLE
Add a final key derivation

### PR DESCRIPTION
**Pull request by charlie-j**
This pull request corresponds to #269.

Changes:
 * `PRK_4x3m` is now `PRK_3m` only, i.e. only used for computing the MAC.
 * An additional key `PRK_out` is defined, which can be seen as the final session key, computed based on `PRK_3m` and `TH_4`.
 * The export now only depends on `PRK_out`. 
 
 Comments:
 * The name `PRK_out` is completely arbitrary.
 * The `TH_4` input that was inside the exporter has been replaced by the empty string. It is a shortcut that allows to use the existing syntax, but it is also arbitrary.
 * This update also corresponds to the option 2) of #270. Indeed, computing both the MAC and `PRK_out` could be performed inside a TEE, and a leak of `PRK_out` once it is outside of the TEE would not allow an attacker to forge any MAC it wants, as `PRK_3m` and `PRK_out` are now disjoint values.

### CODE REVIEW

**Review by emanjon — APPROVED** [review]

**Comment by emanjon** [comment]
This looks like a good thing to do for several reasons. It also lowers memory requirements as the implementation only has to store PRK_out instead of (PRK_4x3m, TH_4).

**Comment by emanjon** [comment]
`After verifying message_3, the Responder is assured that the Initiator has calculated the key PRK_3m (explicit key confirmation) and that no other party than the Initiator can compute the key.`

I assume that is enough. The document should probably say something about PRK_out as well. I assume the property we get it the the Responder knows that I can compute PRK_out.

**Review by emanjon — CHANGES_REQUESTED** [review]
More text is needed on PRK_Out. What does R know about I and PRK_Out after receiveing flight 3 vs. after recieving flight 5. What does I know about R and PRK_Out after recieving flight 4.

**Comment by charlie-j** [comment]
@emanjon you can check out the last update!

**Comment by gselander** [comment]
I spotted a typo, otherwise the update looks ready to merge.

But following #278 there are quite a few other changes we want to make to the key schedule. To avoid merge conflicts should probably do the changes in sequence. We could start by merging this, although there will be further changes to some of the changes made here.

**Pull request merged**
