### PR TITLE
#375 processing of message_2 and message_3

### PR DESCRIPTION
**Pull request by emanjon**
#375 processing of message_2 and message_3

### CODE REVIEW

**Comment by emanjon** [comment]
I think these sections need more considerations and clarifications. Some people has stated that you cannot derive OSCORE keys if you get an EDHOC error. My understanding was that you could. There are two types of EDHOC errors. One parsing errors to you cannot derive keys and then authentication errors (X.509 identity not authorized, X.509 cert expired, X.509 issuer not trusted, OCSP server offline, etc.). Whatever the answer is it needs to be clear. The current situation where people have different understandings is not good.

With the first type of error, TLS sends an unprotected error. In the second case TLS sends an protected error.

**Comment by gselander** [comment]
Perhaps we should break out the error discussion in a separate issue? 

Just as a reminder, at IETF 110 we had the following candidate EDHOC error classes:

1. Selected cipher suite not supported
2. Message (field) error (syntax error or incorrect protocol field of expected message)
3. Credential/context error (error related to establish certificate/raw public key context for processing message, including certificate expired, revoked, unsupported, corrupt, unknown CA, or other issue in processing the credential)
4. Decrypt error (a cryptographic operation failed, including being unable to correctly verify a signature or a MAC in the protocol message)
5. EAD error (unsupported or missing data)
6. Access denied (credential valid but peer not allowed access)
7. Internal error (error not related to the protocol or the peer)

- 1 is included in the draft
- 3 is related to the authentication errors John mentioned above
- 5 has been brought up again, with a registry for EAD applications to register their own errors
- a new error code is proposed in #401

**Comment by emanjon** [comment]
> Perhaps we should break out the error discussion in a separate issue?
> 
> Just as a reminder, at IETF 110 we had the following candidate EDHOC error classes:
> 
>     1. Selected cipher suite not supported
> 
>     2. Message (field) error (syntax error or incorrect protocol field of expected message)
> 
>     3. Credential/context error (error related to establish certificate/raw public key context for processing message, including certificate expired, revoked, unsupported, corrupt, unknown CA, or other issue in processing the credential)
> 
>     4. Decrypt error (a cryptographic operation failed, including being unable to correctly verify a signature or a MAC in the protocol message)
> 
>     5. EAD error (unsupported or missing data)
> 
>     6. Access denied (credential valid but peer not allowed access)
> 
>     7. Internal error (error not related to the protocol or the peer)
> 
> 
>     * 1 is included in the draft
> 
>     * 3 is related to the authentication errors John mentioned above
> 
>     * 5 has been brought up again, with a registry for EAD applications to register their own errors
> 
>     * a new error code is proposed in [New error code for unknown credential referenced #401](https://github.com/lake-wg/edhoc/pull/401)

Good to take that as part of the #401 discussion. Currently 2-7 are in the draft as "unspecified error".

**Comment by gselander** [comment]
The two points we have been discussing are:

* When does authentication occur?
* When can the keys derived from PRK_out be used?

@marco-tiloca-sics @chrysn Do you have any objections to this PR?

**Comment by gselander** [comment]
Note that the current text seems to assume that error messages are not secured:

OLD
> But as the error message is not authenticated, a received error message might also have been sent by an attacker and the receiver MAY therefore try to continue the protocol.

This text indicates that a derived key cannot be used for protecting the error. Needs to be clarified, e.g. rephrase sentence above as:
NEW
But as the error message is expected to not be authenticated, a received error message might also have been sent by an attacker and the receiver MAY therefore try to continue the protocol.

**Comment by marco-tiloca-sics** [comment]
This PR looks good to me.

Also, the clarification proposed in the comment above [1] looks good.

[1] https://github.com/lake-wg/edhoc/pull/398#issuecomment-1580322669

**Comment by gselander** [comment]
Merging this as no objection was received.

**Pull request merged**
